version: '2'

networks:
  app-tier:
    driver: bridge

services:
  web:
    image: rolmos/moie-lucy-api
    command: 'npm run start'
    volumes:
      - "/var/storage/pdf:/storage/pdf"
      - "/var/storage/uploads:/public/uploads"
    ports:
      - "18210:18210"
    depends_on:
      - mysqldb
    networks:
      - app-tier
    environment:
      PORT: 18210
      HOST: http://3.85.198.54
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USERNAME: 'root'
      DB_PASSWORD: 'Panama2018.'
      DB_DATABASE: 'moie-lucy-v2'
      SEED_DB: false
      DIAN_USER: 1CCC171F7911107313
      DIAN_PASSWORD: 1CCC171F7911107313
      PUBLIC_URL: http://3.85.198.54
      TZ: 'America/Bogota'
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'Panama2018.'
      MYSQL_PASSWORD: 'Panama2018.'
      MYSQL_USER: 'moie-lucy'
      MYSQL_ROOT_HOST: '%'
      DB_NAME: 'moie-lucy-v2'
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - app-tier
    volumes:
#      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
#      #- "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./scripts/moie-v2-qa-bk.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./etc/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      - "/var/db:/var/lib/mysql"
